module.exports = {
   operator_stats: {
      "operatorpvp_smoke_poisongaskill":"Poison gas kills",
      "operatorpvp_mute_gadgetjammed":"Gadget Jammed",
      "operatorpvp_mute_jammerdeployed":"Signal Disruptor Deployed",
      "operatorpvp_sledge_hammerhole":"Destruction by Breaching Hammer",
      "operatorpvp_sledge_hammerkill":"Kills by Breaching Hammer",
      "operatorpvp_thatcher_gadgetdestroywithemp":"Gadgets Destroyed by EMP",
      "operatorpvp_castle_kevlarbarricadedeployed":"Armor Panel Deployed",
      "operatorpvp_ash_bonfirekill":"Kills by Breaching Round",
      "operatorpvp_ash_bonfirewallbreached":"Destruction by Breaching Round",
      "operatorpvp_pulse_heartbeatassist":"Cardiac Sensor Assist Kills",
      "operatorpvp_pulse_heartbeatspot":"Heartbeats Spotted",
      "operatorpvp_thermite_chargedeployed":"Exo-Thermic Charge Deployed",
      "operatorpvp_thermite_chargekill":"Exo-Thermic Charge Kills",
      "operatorpvp_thermite_reinforcementbreached":"Reinforcements Breached by Exo-Thermic Charge",
      "operatorpvp_doc_hostagerevive":"Assets Revived",
      "operatorpvp_doc_selfrevive":"Revive Self",
      "operatorpvp_doc_teammaterevive":"Teammates Revived",
      "operatorpvp_rook_armorboxdeployed":"Armor Pack Deployed",
      "operatorpvp_rook_armortakenourself":"Armor Plate Employed",
      "operatorpvp_rook_armortakenteammate":"Armor Plate Taken by Teammates",
      "operatorpvp_twitch_gadgetdestroybyshockdrone":"Gadgets Destroyed by Shock Drone",
      "operatorpvp_twitch_shockdronekill":"Shock Drone Kills",
      "operatorpvp_montagne_shieldblockdamage":"Bullets Blocked by Extended Shield",
      "operatorpvp_glaz_sniperkill":"Sniper Kills",
      "operatorpvp_glaz_sniperpenetrationkill":"Sniper Penetration Kills",
      "operatorpvp_fuze_clusterchargekill":"Cluster Charge Kills",
      "operatorpvp_kapkan_boobytrapdeployed":"Entry Denial Device Deployed",
      "operatorpvp_kapkan_boobytrapkill":"Entry Denial Device Kills",
      "operatorpvp_tachanka_turretdeployed":"Mounted LMG Deployed",
      "operatorpvp_tachanka_turretkill":"Mounted LMG Kills",
      "operatorpvp_blitz_flashedenemy":"Enemies Blinded by Flash Shield",
      "operatorpvp_blitz_flashfollowupkills":"Flash Shield Blinded Kills",
      "operatorpvp_blitz_flashshieldassist":"Flash Shield Blinded Enemies Killed by Teammate",
      "operatorpvp_iq_gadgetspotbyef":"Gadgets Spotted by Electronics Detector",
      "operatorpvp_jager_gadgetdestroybycatcher":"Gadget Destroyed by Active Defense",
      "operatorpvp_bandit_batterykill":"Shock Wire Kills",
      "operatorpvp_buck_kill":"Kills with the Skeleton Key",
      "operatorpvp_frost_dbno":"Enemies caught in Welcome Mats",
      "operatorpvp_blackbeard_gunshieldblockdamage":"Bullets Stopped by Shield",
      "operatorpvp_valkyrie_camdeployed":"Black Eye cameras deployed",
      "operatorpvp_echo_enemy_sonicburst_affected":"Yokai Was Destroyed",
      "operatorpvp_hibana_detonate_projectile":"X-Kairos Pellets Detonated",
      "operatorpvp_black_mirror_gadget_deployed":"Mirrors Deployed",
      "operatorpvp_cazador_assist_kill":"Cazador Kill Assists",
      "operatorpvp_caveira_interrogations":"Interrogations",
      "operatorpvp_capitao_lethaldartkills":"Lethal Dart Kills"
   }
}